### ISSUE TITLE
Sans-webcam usage

### ISSUE THREAD

**Issue by 1j01** [googlecreativelab/aiexperiments-giorgio-cam#2]
If you don't have a webcam, it just says "Since you did't [sic] allow access to the camera, this experiment won't work", which isn't particularly accurate. And it could work without one, by uploading images.

**Comment by tambien** [comment]
Fixed the spelling error! thanks for bringing that to my attention. 

I think we'd like to leave Giorgio Cam as an experience which requires the camera access since it makes it a fun back and forth musical experience with the Cloud Vision API. 

If you want to just see what sort of labels the Vision API will produce from images that you upload, there is a tool on [their website](https://cloud.google.com/vision/) where you can drop in an image file.
